@api = http://localhost:5000/api/users

### POST Create user
POST {{api}}/create
Content-Type: application/json

{
  "company": "testing",
  "dni": "0Z",
  "name": "Toni"
}

### POST Login
POST {{api}}/login
Content-Type: application/json

{
  "dni": "00000000A",
  "password": "00000000A"
}